import type { ExcalidrawElement } from "@excalidraw/excalidraw/element/types";
import type { AppState, BinaryFiles } from "@excalidraw/excalidraw/types";

export type ProjectId = string & { readonly _brand?: "ProjectId" };
export type DesignId = string & { readonly _brand?: "DesignId" };

/** Project accent colours – keys map to the `--pc-*` tokens defined in `src/css/app.scss`. */
export type ProjectColor =
  | "gray"
  | "violet"
  | "blue"
  | "teal"
  | "green"
  | "yellow"
  | "orange"
  | "red"
  | "pink";

export interface Project {
  id: ProjectId;
  name: string;
  emoji: string;
  color: ProjectColor;
  tags: string[];
  /** manual sort position (fractional-free: plain integer, renumbered on reorder) */
  order: number;
  createdAt: number;
  updatedAt: number;
  archivedAt?: number;
}

export interface Design {
  id: DesignId;
  projectId: ProjectId;
  name: string;
  tags: string[];
  order: number;
  createdAt: number;
  updatedAt: number;
  archivedAt?: number;
  /** `getSceneVersion(elements)` of the last persisted scene – used to skip no-op writes */
  sceneVersion: number;
  /**
   * small PNG preview, regenerated by the editor. Stored as raw bytes rather
   * than a Blob: Blobs in IndexedDB are unreliable in Safari and don't survive
   * structured cloning in every environment.
   */
  thumbnail?: ArrayBuffer;
  thumbnailUpdatedAt?: number;
}

/** The persisted Excalidraw scene of a design. Kept in its own store so list views stay light. */
export interface Scene {
  designId: DesignId;
  elements: readonly ExcalidrawElement[];
  /** whitelisted subset of AppState (see `data/scenes.ts`) */
  appState: Partial<AppState>;
  files: BinaryFiles;
}

export type SortKey = "updatedAt" | "name" | "createdAt" | "manual";

export type ThemeSetting = "light" | "dark" | "system";

export interface Settings {
  theme: ThemeSetting;
  projectsSort: SortKey;
  designsSort: SortKey;
  showArchivedProjects: boolean;
  showArchivedDesigns: boolean;
  /** `navigator.storage.persist()` has been requested once */
  persistRequested: boolean;
}

export const DEFAULT_SETTINGS: Settings = {
  theme: "system",
  projectsSort: "updatedAt",
  designsSort: "updatedAt",
  showArchivedProjects: false,
  showArchivedDesigns: false,
  persistRequested: false,
};

/* ---------------------------------------------------------------------------
 * Backup format (see docs/PRD.md §4.5)
 * ------------------------------------------------------------------------- */

export const BACKUP_FORMAT_VERSION = 1;

export interface BackupDesignEntry
  extends Omit<Design, "thumbnail" | "thumbnailUpdatedAt"> {
  /** path of the `.excalidraw` file inside the zip */
  file: string;
  /** optional path of the thumbnail png inside the zip */
  thumbnailFile?: string;
}

export interface BackupProjectEntry extends Project {
  designs: BackupDesignEntry[];
}

export interface BackupManifest {
  formatVersion: typeof BACKUP_FORMAT_VERSION;
  app: string;
  exportedAt: string;
  projects: BackupProjectEntry[];
}

export type ImportMode = "merge" | "replace";

export interface ImportSummary {
  projectsAdded: number;
  projectsUpdated: number;
  designsAdded: number;
  designsUpdated: number;
  skipped: number;
  warnings: string[];
}
